const numberBttns = document.querySelectorAll('[data-number]')
const operationBttns = document.querySelectorAll('[data-operation]')
const equalsButtn = document.querySelector('[data-equals]')
const deleteButtn = document.querySelector('[data-delete]')
const allclearButtn = document.querySelector('[data-allclear]')
const previousOperandTextElement = document.querySelector('[data-prevop]')
const currentOperandTextElement = document.querySelector('[data-currentop]')